### PR TITLE
Bug 103 hotfix now .

### LINKED ISSUE #19: This is an assigned issue
lets make this an issue

### PR DESCRIPTION
**Pull request by jbarson**
fixes #19 .

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -7,6 +7,7 @@
     console.log("go baby go baby baby baby");
     console.warn("this is a bug!");
     console.warn("this is a worse bug");
+    console.info("I like turtles");
```
Comment (jbarson) [inline main.js:10]: Can we make this reptiles?

Comment (jbarson) [reply main.js:10]: This is fine

File: main.js [hunk 2]
```diff
@@ -7,6 +7,7 @@
     console.log("go baby go baby baby baby");
     console.warn("this is a bug!");
```
Comment (jbarson) [inline main.js:8]: Well fix it then!
```suggestion
    console.warn("this is not a bug!");
```
